packages:
  - packages/*

catalog:
  '@types/jest': ^30.0.0
  '@types/node': ^20.19.1
  '@types/vscode': ^1.88.0
  jest: ^30.0.0
  ts-jest: ^29.4.0
  typescript: ^5.1.3
  vscode-nls-dev: ^4.0.4
  vsce: ^2.15.0
  vscode-nls: ^5.2.0
  bumpp: ^10.2.0
