packages:
  - packages/*

catalog:
  '@types/jest': 30.0.0
  '@types/node': 24.0.3
  '@types/vscode': 1.101.0
  bumpp: 10.2.0
  jest: 30.0.2
  ts-jest: 29.4.0
  typescript: 5.8.3
  vsce: 2.15.0
  vscode-nls: 5.2.0
  vscode-nls-dev: 4.0.4
